name: diente
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  awesome_dialog: ^3.2.1
  bloc: ^8.1.4
  cloud_firestore: ^5.4.2
  equatable: ^2.0.5
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  google_fonts: 4.0.4
  image_cropper: ^3.0.1
  image_picker: ^1.1.2
  panara_dialogs: ^0.1.5
  pinput: ^5.0.0
  restart_app: ^1.2.1
  # image_cropper_for_web: ^0.0.4

  firebase_core: any
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/POPPINS-REGULAR.TTF
        - asset: assets/fonts/POPPINS-BOLD.TTF
          weight: 700
        - asset: assets/fonts/POPPINS-EXTRALIGHT.TTF
          weight: 200
        - asset: assets/fonts/POPPINS-LIGHT.TTF
          weight: 300
        - asset: assets/fonts/POPPINS-MEDIUM.TTF
          weight: 500
        - asset: assets/fonts/POPPINS-SEMIBOLD.TTF
          weight: 600
        - asset: assets/fonts/POPPINS-THIN.TTF
          weight: 100
