name: diente
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.4.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_otp_text_field: ^1.1.3+2
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  google_fonts: ^5.0.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  pinput: ^5.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/POPPINS-REGULAR.TTF
        - asset: assets/fonts/POPPINS-BOLD.TTF
          weight: 700
        - asset: assets/fonts/POPPINS-EXTRALIGHT.TTF
          weight: 200
        - asset: assets/fonts/POPPINS-LIGHT.TTF
          weight: 300
        - asset: assets/fonts/POPPINS-MEDIUM.TTF
          weight: 500
        - asset: assets/fonts/POPPINS-SEMIBOLD.TTF
          weight: 600
        - asset: assets/fonts/POPPINS-THIN.TTF
          weight: 100
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Medium.ttf
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
        - asset: assets/fonts/NotoSansArabic-Black.ttf
        - asset: assets/fonts/NotoSansArabic-ExtraBold.ttf
        - asset: assets/fonts/NotoSansArabic-ExtraLight.ttf
        - asset: assets/fonts/NotoSansArabic-Light.ttf
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/NotoSansArabic-SemiBold.ttf
        - asset: assets/fonts/NotoSansArabic-Thin.ttf
